### ISSUE TITLE
git submodule update --init --recursive takes a long time in CI

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/kubernetes#49]
This takes 4 minutes out of the 5 minutes we need for the CI passes. Maybe a shallow checkout (`--depth`) would help here?

**Comment by squaremo** [comment]
Oh whoops, yeah that's because of the submodule used for schema files. If we can restrict depth for that it would probably help -- or just vendor the files we need.

**Comment by squaremo** [comment]
We only use the `*-local` files, but it's tricky to git clone or otherwise download just those. Possibly vendoring into a subtree is the way.

Slightly further out idea: if there were an image layer with each schema version, it might be possible to package things such that only the necessary layer(s) were used.

**Comment by squaremo** [comment]
`make dist` now:

 1. Downloads a tarball rather than using a submodule;
 2. Gets it from jkcfg/kubernetes-schema, which has just the local schemas i.e., way fewer files;
 3. deduplicates the files that didn't change between versions

as of #60. Woo!
